### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a background container 
- [x] Style the background color to green
- [x] Create a div for storing the car
- [x] Insert Car image with a img tag
