### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a variable for the div containing the car
- [x] Query select that div and add an event listener for detecting the arrows
- [x] Rotate the car div with CSS based on the arrow that is pressed
