### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create a coordinates data model for the car's x and y coordinates on the page
- [x] Apply absolute positioning for my image
- [x] Apply an offset property to my car to move every 16 milliseconds for a smooth movement.
