### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add in the ability to pause the offset when the space bar is pressed
- [x] Create an if statement for detecting if the space bar is pressed
- [x] Pause the off set property when the the space bar is pressed
