### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Create a function for adding x and y coordinate increments to the car based on the arrows pressed
- [x] Assign positive x and y when right and up are pressed respectively
- [x] Assign negative x and y when left and down are pressed respectively
